### ISSUE TITLE
AnonymousTypeUtils.CreateType can fail in a multithreaded environment

### ISSUE THREAD

**Issue by 2222222** [dotlattice/LatticeUtils#2]
When two threads are trying to create the same type at the same time, you can occasionally get errors like this:

```
System.InvalidOperationException was unhandled by user code
  HResult=-2146233079
  Message=Operation is not valid due to the current state of the object.
  Source=mscorlib
  StackTrace:
       at System.Reflection.Emit.TypeBuilderInstantiation.MakeGenericType(Type type, Type[] typeArguments)
       at System.Reflection.Emit.TypeBuilder.MakeGenericType(Type[] typeArguments)
       at LatticeUtils.AnonymousTypeUtils.CreateType(IEnumerable`1 typePairs, Boolean isMutable)
       at LatticeUtils.AnonymousTypeUtils.CreateType(IEnumerable`1 typePairs)
       ...
```

The `GetOrCreateGenericTypeDefinition` method calls `ModuleBuilder.GetType()` to see if a type has already been created.  If a type has been defined but not created, then `ModuleBuilder.GetType()` will return a `TypeBuilder` instead of a completed Type.  And when that happens, creating an object of that type will fail.

**Comment by dotlattice** [comment]
I hadn't realized that ModuleBuilder would return the partially defined type there. That would definitely cause some problems.

I replaced the double check locking with just a simple lock, which should fix this issue.  And I added a unit test that was consistently reproducing the problem for me before this fix.
